### PR TITLE
make BOOST_PLAT_WINDOWS_DESKTOP available in older SDKs for backwards compatibility

### PR DESCRIPTION
**Pull request by jeking3**
Also fixed up some of the documentation issues in the new UWP macros.

### CODE REVIEW

**Comment by jeking3** [comment]
@pdimov @Lastique please review.

**Comment by Lastique** [comment]
I have no comments wrt. implementation. Aren't docs need to be updated?

**Comment by pdimov** [comment]
It looks good to me, except that I still think it's not deprecated.

**Comment by jeking3** [comment]
@Lastique I thought I got everything, what did I miss?

**Comment by Lastique** [comment]
@jeking3 I don't know, I just noticed there are QuickBook files and those are not updated by this PR.

**Comment by jeking3** [comment]
@Lastique My impression is that the documentation is built from the comments in the source in these cases, which were updated.  

@pdimov There is only one mention of deprecation in the unit test, it is no longer in the header for desktop, so I will remove it from the unit test comment and it won't be deprecated any more.

**Comment by Lastique** [comment]
> My impression is that the documentation is built from the comments in the source in these cases, which were updated.

Oh, ok, thanks.

**Comment by jeking3** [comment]
Once the current build completes hopefully all of the concerns are resolved.  I did leave `BOOST_PLAT_WINDOWS_RUNTIME` deprecated because it is incorrect and does not line up with a single `WINAPI_FAMILY` so it needs to be removed in the future.  `BOOST_PLAT_WINDOWS_DESKTOP` being available in older SDKs is no longer marked deprecated.

**Comment by pdimov** [comment]
I can confirm that the documentation reflects the changes. I get one Quickbook warning,

```doc\predef.qbk: warning: Invalid attributes for 'article document info': purpose
, category, dirname```

but that probably has nothing to do with this patch.

**Comment by pdimov** [comment]
The tests pass for msvc-8.0, msvc-10.0, msvc-11.0, msvc-12.0, msvc-14.0, msvc-14.1. This looks good to go.

**Pull request merged**
